# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: auto-deploy-test
    steps:
      #下载代码
      - name: Checkout
        uses: actions/checkout@v2
      # - uses: actions/checkout@master
      #打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: "16.0"
      - run: npm install #安装依赖
      - run: npm run build
      # 部署到githubpages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3   #使用部署到GitHubpages的actions
        with:
          brach: gh-pages
          publish_dir: ./dist
          github_token: ${{ secrets.CICDTEST }}
          #user_name: ${{secrets.MY_USER_NAME}}
          commit_message: 自动部署
